#!/usr/bin/env node

'use strict';

const fs = require('fs');
const path = require('path');
const { loadAgent } = require('./parse-agent');
const {
  DEFAULT_CODEX_AGENT_CONFIG,
  resolveCodexAgentSettings,
} = require('./model-config');

function renderCodexToml(parsedAgent, options = {}) {
  const settings = resolveCodexAgentSettings(
    parsedAgent,
    options.agentConfig || DEFAULT_CODEX_AGENT_CONFIG,
  );
  const maxChars = options.maxChars === undefined ? 4000 : Number(options.maxChars);
  const description = (parsedAgent.frontmatter.description || '').replace(/"/g, '\\"');
  const instructions = maxChars > 0 && parsedAgent.body.length > maxChars
    ? parsedAgent.body.slice(0, maxChars) + '\n\n[Truncated by Citadel projection. See canonical agent definition for full instructions.]'
    : parsedAgent.body;
  const allowedTools = Array.isArray(parsedAgent.frontmatter.tools)
    ? parsedAgent.frontmatter.tools
    : [];
  const disallowedTools = Array.isArray(parsedAgent.frontmatter.disallowedTools)
    ? parsedAgent.frontmatter.disallowedTools
    : [];
  const hasToolPolicy = allowedTools.length > 0 || disallowedTools.length > 0;
  const policyComments = hasToolPolicy
    ? [
      '# WARNING: Codex agent TOML does not machine-enforce Citadel tool allow/deny lists.',
      `# Citadel allowed tools: ${allowedTools.length > 0 ? allowedTools.join(', ') : '(not declared)'}`,
      `# Citadel disallowed tools: ${disallowedTools.length > 0 ? disallowedTools.join(', ') : '(not declared)'}`,
    ]
    : [];
  const policyInstruction = hasToolPolicy
    ? [
      '[Citadel tool policy advisory]',
      'This Codex projection cannot machine-enforce the canonical tool allow/deny list.',
      allowedTools.length > 0 ? `Use only these declared tools: ${allowedTools.join(', ')}.` : null,
      disallowedTools.length > 0 ? `Do not use these declared tools: ${disallowedTools.join(', ')}.` : null,
      'The active Codex host permission policy remains authoritative.',
      '',
    ].filter((line) => line !== null).join('\n')
    : '';

  return [
    '# Generated by Citadel. Do not edit manually.',
    `# Source: agents/${parsedAgent.frontmatter.name || parsedAgent.name}.md`,
    ...policyComments,
    '',
    `name = "${parsedAgent.frontmatter.name || parsedAgent.name}"`,
    `description = "${description}"`,
    `model = "${settings.model}"`,
    `model_reasoning_effort = "${settings.reasoningEffort}"`,
    '',
    'developer_instructions = """',
    policyInstruction,
    instructions,
    '"""',
    '',
  ].join('\n');
}

function ensureDir(dir) {
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
}

function projectAgentToCodex(agentPath, targetBaseDir, options = {}) {
  const parsedAgent = loadAgent(agentPath);
  if (parsedAgent.errors && parsedAgent.errors.length > 0) {
    throw new Error(`Agent "${parsedAgent.name}" has validation errors: ${parsedAgent.errors.join(', ')}`);
  }
  const targetPath = path.join(targetBaseDir, `${parsedAgent.frontmatter.name || parsedAgent.name}.toml`);
  const toml = renderCodexToml(parsedAgent, options);

  if (!options.dryRun) {
    ensureDir(path.dirname(targetPath));
    fs.writeFileSync(targetPath, toml, 'utf8');
  }

  return {
    parsedAgent,
    output: {
      tomlPath: targetPath,
      toml,
    },
  };
}

module.exports = Object.freeze({
  renderCodexToml,
  projectAgentToCodex,
});
