#!/usr/bin/env node

'use strict';

// Installs the Citadel plugin into a project for opencode.
//
// opencode auto-discovers plugins from `.opencode/{plugin,plugins}/*.{ts,js}`
// (config/plugin.ts), so the install is one small stub that re-exports the
// plugin from the Citadel checkout. Writing a stub rather than copying the
// adapter means a Citadel upgrade takes effect without reinstalling.
//
// opencode.json is merged, never rewritten: it is a user-owned file and
// hard-fails opencode on invalid content, so every key Citadel does not own is
// preserved exactly.

const fs = require('fs');
const path = require('path');

const PLUGIN_STUB_NAME = 'citadel.js';
const GENERATED_MARKER = 'Generated by Citadel. Do not edit manually.';
const MCP_SERVER_NAME = 'citadel-state';

function ensureDir(dir) {
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
}

function readJsonIfPresent(filePath) {
  if (!fs.existsSync(filePath)) return { value: null, raw: null };
  const raw = fs.readFileSync(filePath, 'utf8');
  try {
    return { value: JSON.parse(raw), raw };
  } catch (error) {
    // Refuse to touch a file we cannot parse rather than clobbering user config.
    throw new Error(`${filePath} is not valid JSON (${error.message}); fix or remove it before installing`);
  }
}

// The stub is ESM: opencode loads plugins as modules. `citadelRoot` is embedded
// as a file URL so the import works regardless of the project's own module type.
function renderPluginStub(citadelRoot) {
  const entry = path.join(citadelRoot, 'runtimes', 'opencode', 'plugin', 'index.mjs');
  const specifier = `file://${entry.replace(/\\/g, '/')}`;
  return [
    `// ${GENERATED_MARKER}`,
    '// Re-exports the Citadel opencode plugin from the Citadel checkout, so a',
    '// Citadel upgrade takes effect without reinstalling this stub.',
    `export { CitadelPlugin } from ${JSON.stringify(specifier)};`,
    `export { CitadelPlugin as default } from ${JSON.stringify(specifier)};`,
    '',
  ].join('\n');
}

// Shape per opencode's McpLocalConfig (core/v1/config/mcp.ts): `command` is a
// single argv array — there is no separate `args` key — `environment` rather than
// `env`, and `timeout` is milliseconds. That schema is a plain Struct, so an
// unknown key fails the decode and opencode hard-fails at startup.
function citadelMcpServer(citadelRoot, projectRoot) {
  return {
    type: 'local',
    command: ['node', path.join(citadelRoot, 'mcp-servers', MCP_SERVER_NAME, 'index.js')],
    environment: {
      CITADEL_PROJECT_ROOT: projectRoot,
      CITADEL_ROOT: citadelRoot,
      CITADEL_RUNTIME: 'opencode',
    },
    enabled: true,
  };
}

/**
 * Merge Citadel's keys into an existing opencode.json without disturbing others.
 * Returns the merged object plus what changed, so callers can report a dry run.
 */
function mergeOpencodeConfig(existing, { citadelRoot, projectRoot }) {
  const config = existing && typeof existing === 'object' && !Array.isArray(existing)
    ? { ...existing }
    : {};
  const changes = [];

  if (!config.$schema) {
    config.$schema = 'https://opencode.ai/config.json';
    changes.push('added $schema');
  }

  // MCP: only the Citadel server is touched; other servers stay untouched.
  const mcp = { ...(config.mcp || {}) };
  const desired = citadelMcpServer(citadelRoot, projectRoot);
  if (JSON.stringify(mcp[MCP_SERVER_NAME]) !== JSON.stringify(desired)) {
    mcp[MCP_SERVER_NAME] = desired;
    changes.push(`set mcp.${MCP_SERVER_NAME}`);
  }
  config.mcp = mcp;

  return { config, changes };
}

function installOpencodePlugin(options = {}) {
  const citadelRoot = path.resolve(options.citadelRoot || path.resolve(__dirname, '..', '..', '..'));
  const projectRoot = path.resolve(options.projectRoot || process.cwd());
  const dryRun = options.dryRun === true;

  const pluginDir = path.join(projectRoot, '.opencode', 'plugin');
  const pluginPath = path.join(pluginDir, PLUGIN_STUB_NAME);
  const configPath = path.join(projectRoot, 'opencode.json');

  const stub = renderPluginStub(citadelRoot);
  const { value: existingConfig } = readJsonIfPresent(configPath);
  const { config, changes } = mergeOpencodeConfig(existingConfig, { citadelRoot, projectRoot });

  const existingStub = fs.existsSync(pluginPath) ? fs.readFileSync(pluginPath, 'utf8') : null;
  const stubChanged = existingStub !== stub;
  const serialized = `${JSON.stringify(config, null, 2)}\n`;

  const writes = [];
  if (stubChanged) writes.push({ path: pluginPath, action: existingStub === null ? 'create' : 'update' });
  if (changes.length > 0) {
    writes.push({ path: configPath, action: existingConfig === null ? 'create' : 'merge', changes });
  }

  if (!dryRun) {
    if (stubChanged) {
      ensureDir(pluginDir);
      fs.writeFileSync(pluginPath, stub, 'utf8');
    }
    if (changes.length > 0) fs.writeFileSync(configPath, serialized, 'utf8');
  }

  return {
    citadelRoot,
    projectRoot,
    pluginPath,
    configPath,
    config,
    changes,
    writes,
    dryRun,
  };
}

module.exports = Object.freeze({
  GENERATED_MARKER,
  MCP_SERVER_NAME,
  PLUGIN_STUB_NAME,
  citadelMcpServer,
  installOpencodePlugin,
  mergeOpencodeConfig,
  renderPluginStub,
});
