#!/usr/bin/env node

'use strict';

// Installs the Citadel plugin into a project for opencode.
//
// opencode auto-discovers plugins from `.opencode/{plugin,plugins}/*.{ts,js}`
// (config/plugin.ts), so the install is one small stub that re-exports the
// plugin from the Citadel checkout. Writing a stub rather than copying the
// adapter means a Citadel upgrade takes effect without reinstalling.
//
// opencode.json is merged, never rewritten: it is a user-owned file and
// hard-fails opencode on invalid content, so every key Citadel does not own is
// preserved exactly.

const fs = require('fs');
const path = require('path');
const {
  assertPortableSharedOutputs,
  classifyOutputs,
  ensureMachineLocalExcludes,
  ensureProjectDelegate,
} = require('../../../core/runtime/install-contract');

const PLUGIN_STUB_NAME = 'citadel.js';
const GENERATED_MARKER = 'Generated by Citadel. Do not edit manually.';
const MCP_SERVER_NAME = 'citadel-state';

function ensureDir(dir) {
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
}

function copyDirectory(source, target, dryRun, writes) {
  if (!fs.existsSync(source)) return;
  for (const entry of fs.readdirSync(source, { withFileTypes: true })) {
    const sourcePath = path.join(source, entry.name);
    const targetPath = path.join(target, entry.name);
    if (entry.isDirectory()) {
      copyDirectory(sourcePath, targetPath, dryRun, writes);
      continue;
    }
    const content = fs.readFileSync(sourcePath);
    const changed = !fs.existsSync(targetPath)
      || !content.equals(fs.readFileSync(targetPath));
    if (!changed) continue;
    writes.push({ path: targetPath, action: fs.existsSync(targetPath) ? 'update' : 'create' });
    if (!dryRun) {
      ensureDir(path.dirname(targetPath));
      fs.writeFileSync(targetPath, content);
    }
  }
}

function syncProjectSkills(citadelRoot, projectRoot, dryRun) {
  const source = path.join(citadelRoot, 'skills');
  const target = path.join(projectRoot, '.citadel', 'skills');
  const writes = [];
  copyDirectory(source, target, dryRun, writes);
  return {
    path: target,
    action: writes.length > 0 ? 'sync' : 'up-to-date',
    writes,
  };
}

function readJsonIfPresent(filePath) {
  if (!fs.existsSync(filePath)) return { value: null, raw: null };
  const raw = fs.readFileSync(filePath, 'utf8');
  try {
    return { value: JSON.parse(raw), raw };
  } catch (error) {
    // Refuse to touch a file we cannot parse rather than clobbering user config.
    throw new Error(`${filePath} is not valid JSON (${error.message}); fix or remove it before installing`);
  }
}

// The stub is ESM: opencode loads plugins as modules. `citadelRoot` is embedded
// as a file URL so the import works regardless of the project's own module type.
function renderPluginStub(citadelRoot) {
  const entry = path.join(citadelRoot, 'runtimes', 'opencode', 'plugin', 'index.mjs');
  const specifier = `file://${entry.replace(/\\/g, '/')}`;
  return [
    `// ${GENERATED_MARKER}`,
    '// Re-exports the Citadel opencode plugin from the Citadel checkout, so a',
    '// Citadel upgrade takes effect without reinstalling this stub.',
    `export { CitadelPlugin } from ${JSON.stringify(specifier)};`,
    `export { CitadelPlugin as default } from ${JSON.stringify(specifier)};`,
    '',
  ].join('\n');
}

// opencode scans every path in `skills.paths` with `**/SKILL.md`
// (`skill/index.ts:211-219`). External project installs use a project-local
// projection so the shared config remains portable when either checkout moves.
//
// Requires opencode >= 1.18.30, where `skills.paths` was verified to exist
// (`core/v1/config/skills.ts` at tag v1.18.30 — the build phase 5 ran against).
// The top-level config is a plain Schema.Struct, so on a build without the key
// this fails the decode and opencode hard-fails at startup. That is the same trap
// the MCP `args` key set, which is why the version was checked before relying on
// it rather than after.
function citadelSkillsPath(citadelRoot, projectRoot = null) {
  const absolute = path.join(citadelRoot, 'skills');
  if (!projectRoot) return absolute;
  return path.resolve(citadelRoot) === path.resolve(projectRoot)
    ? './skills'
    : './.citadel/skills';
}

// The shared delegate pointer can be updated by another runtime before
// OpenCode is reinstalled. Keep every Citadel root evidenced by either the
// pointer or OpenCode's own stub so stale skills paths from the old stub are
// still migrated away.
function readPreviousCitadelRoot(projectRoot, pluginPath) {
  const roots = [];
  const addRoot = candidate => {
    if (typeof candidate !== 'string' || candidate.trim() === '') return;
    const root = path.resolve(candidate.trim());
    if (!roots.includes(root)) roots.push(root);
  };

  const pointerPath = path.join(projectRoot, '.citadel', 'plugin-root.txt');
  if (fs.existsSync(pointerPath)) {
    addRoot(fs.readFileSync(pointerPath, 'utf8'));
  }

  if (fs.existsSync(pluginPath)) {
    const stub = fs.readFileSync(pluginPath, 'utf8');
    const match = stub.match(/file:\/\/(.+?)\/runtimes[\\/]opencode[\\/]plugin[\\/]index\.mjs/i);
    if (match) {
      let root = match[1].replace(/\\/g, '/');
      if (/^\/[A-Za-z]:\//.test(root)) root = root.slice(1);
      addRoot(root);
    }
  }

  return roots;
}

// Shape per opencode's McpLocalConfig (core/v1/config/mcp.ts): `command` is a
// single argv array — there is no separate `args` key — `environment` rather than
// `env`, and `timeout` is milliseconds. That schema is a plain Struct too, so an
// unknown key fails the decode and opencode hard-fails at startup.
function citadelMcpServer(citadelRoot, projectRoot) {
  const projectIsCitadel = path.resolve(citadelRoot) === path.resolve(projectRoot);
  return {
    type: 'local',
    command: ['node', projectIsCitadel
      ? './mcp-servers/citadel-state/index.js'
      : './.citadel/scripts/citadel-state.js'],
    environment: {
      CITADEL_PROJECT_ROOT: '.',
      CITADEL_RUNTIME: 'opencode',
    },
    enabled: true,
  };
}

/**
 * Merge Citadel's keys into an existing opencode.json without disturbing others.
 * Returns the merged object plus what changed, so callers can report a dry run.
 */
function mergeOpencodeConfig(existing, {
  citadelRoot,
  projectRoot,
  previousCitadelRoots = [],
  previousCitadelRoot = null,
  skipSkills = false,
}) {
  const config = existing && typeof existing === 'object' && !Array.isArray(existing)
    ? { ...existing }
    : {};
  const changes = [];

  if (!config.$schema) {
    config.$schema = 'https://opencode.ai/config.json';
    changes.push('added $schema');
  }

  // MCP: only the Citadel server is touched; other servers stay untouched.
  const mcp = { ...(config.mcp || {}) };
  const desired = citadelMcpServer(citadelRoot, projectRoot);
  if (JSON.stringify(mcp[MCP_SERVER_NAME]) !== JSON.stringify(desired)) {
    mcp[MCP_SERVER_NAME] = desired;
    changes.push(`set mcp.${MCP_SERVER_NAME}`);
  }
  config.mcp = mcp;

  // Skills: append Citadel's skills directory, preserving any the user added.
  // Additive and deduped, because this array is user-owned too.
  if (!skipSkills) {
    const skillsPath = citadelSkillsPath(citadelRoot, projectRoot);
    const existingPaths = Array.isArray(config.skills?.paths) ? [...config.skills.paths] : [];
    const priorRoots = [
      ...(Array.isArray(previousCitadelRoots) ? previousCitadelRoots : [previousCitadelRoots]),
      previousCitadelRoot,
    ];
    const staleSkillRoots = [citadelRoot, ...priorRoots]
      .filter(root => typeof root === 'string' && root.trim() !== '')
      .map((root) => path.resolve(root, 'skills'));
    const retainedPaths = existingPaths.filter((item) => (
      typeof item !== 'string'
      || !path.isAbsolute(item)
      || !staleSkillRoots.includes(path.resolve(item))
    ));
    if (retainedPaths.length !== existingPaths.length) {
      changes.push('removed stale absolute Citadel skills path');
    }
    if (!retainedPaths.includes(skillsPath)) {
      retainedPaths.push(skillsPath);
      changes.push('added skills.paths entry for Citadel skills');
    }
    config.skills = { ...(config.skills || {}), paths: retainedPaths };
  }

  return { config, changes };
}

function installOpencodePlugin(options = {}) {
  const citadelRoot = path.resolve(options.citadelRoot || path.resolve(__dirname, '..', '..', '..'));
  const projectRoot = path.resolve(options.projectRoot || process.cwd());
  const dryRun = options.dryRun === true;

  const pluginDir = path.join(projectRoot, '.opencode', 'plugin');
  const pluginPath = path.join(pluginDir, PLUGIN_STUB_NAME);
  const configPath = path.join(projectRoot, 'opencode.json');
  const previousCitadelRoots = readPreviousCitadelRoot(projectRoot, pluginPath);

  const machineLocalExcludes = ensureMachineLocalExcludes(projectRoot, { dryRun });
  const delegate = path.resolve(projectRoot) === path.resolve(citadelRoot)
    ? null
    : ensureProjectDelegate(projectRoot, citadelRoot, 'citadel-state.js', { dryRun });
  const skills = path.resolve(projectRoot) === path.resolve(citadelRoot) || options.skipSkills === true
    ? { path: path.join(projectRoot, 'skills'), action: 'source checkout', writes: [] }
    : syncProjectSkills(citadelRoot, projectRoot, dryRun);

  const stub = renderPluginStub(citadelRoot);
  const { value: existingConfig } = readJsonIfPresent(configPath);
  const { config, changes } = mergeOpencodeConfig(existingConfig, {
    citadelRoot,
    projectRoot,
    previousCitadelRoots,
    skipSkills: options.skipSkills === true,
  });

  const existingStub = fs.existsSync(pluginPath) ? fs.readFileSync(pluginPath, 'utf8') : null;
  const stubChanged = existingStub !== stub;
  const serialized = `${JSON.stringify(config, null, 2)}\n`;

  const outputs = classifyOutputs([
    { path: '.opencode/plugin/citadel.js', runtime: 'opencode', ownership: 'machine-local', content: stub },
    { path: 'opencode.json', runtime: 'opencode', ownership: 'shared', content: {
      mcp: { [MCP_SERVER_NAME]: config.mcp[MCP_SERVER_NAME] },
      skills: { paths: [citadelSkillsPath(citadelRoot, projectRoot)] },
    } },
    ...(delegate ? [
      { path: '.citadel/plugin-root.txt', runtime: 'opencode', ownership: 'machine-local', content: citadelRoot },
      { path: '.citadel/scripts/package.json', runtime: 'opencode', ownership: 'machine-local', content: { type: 'commonjs' } },
      { path: '.citadel/scripts/citadel-state.js', runtime: 'opencode', ownership: 'machine-local', content: delegate },
    ] : []),
    ...(path.resolve(projectRoot) === path.resolve(citadelRoot) || options.skipSkills === true ? [] : [
      { path: '.citadel/skills', runtime: 'opencode', ownership: 'machine-local', content: skills.path },
    ]),
  ]);
  assertPortableSharedOutputs(outputs);

  const writes = [];
  if (stubChanged) writes.push({ path: pluginPath, action: existingStub === null ? 'create' : 'update' });
  if (changes.length > 0) {
    writes.push({ path: configPath, action: existingConfig === null ? 'create' : 'merge', changes });
  }
  if (delegate) writes.push(...delegate.writes);
  if (skills.writes.length > 0) {
    writes.push({
      path: skills.path,
      action: skills.action,
      changes: [`${skills.writes.length} skill files`],
    });
  }

  if (!dryRun) {
    if (stubChanged) {
      ensureDir(pluginDir);
      fs.writeFileSync(pluginPath, stub, 'utf8');
    }
    if (changes.length > 0) fs.writeFileSync(configPath, serialized, 'utf8');
  }

  return {
    citadelRoot,
    projectRoot,
    pluginPath,
    configPath,
    config,
    changes,
    writes,
    outputs,
    machineLocalExcludes,
    delegate,
    skills,
    dryRun,
  };
}

module.exports = Object.freeze({
  GENERATED_MARKER,
  citadelSkillsPath,
  MCP_SERVER_NAME,
  PLUGIN_STUB_NAME,
  citadelMcpServer,
  installOpencodePlugin,
  mergeOpencodeConfig,
  renderPluginStub,
});
