#!/usr/bin/env node

'use strict';

// Projects Citadel's canonical agents/*.md into .opencode/agent/*.md.
//
// opencode's agent loader (config/agent.ts) globs {agent,agents}/**/*.md, takes
// the agent NAME FROM THE FILE PATH rather than frontmatter, and uses the
// markdown body as the prompt. Its schema (core/v1/config/agent.ts) carries a
// Record rest, so unknown frontmatter keys are tolerated and folded into
// `options` — but only the documented keys are emitted here.

const fs = require('fs');
const path = require('path');
const { loadAgent } = require('../../../core/agents/parse-agent');

const GENERATED_HEADER = 'Generated by Citadel. Do not edit manually.';

// opencode agent modes. Citadel agents are all spawned as subagents.
const SUBAGENT_MODE = 'subagent';

function ensureDir(dir) {
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
}

// YAML scalar quoting for a frontmatter value that may contain colons, hashes,
// newlines, or quotes. Double-quoted style with escapes is valid YAML and avoids
// depending on a YAML writer.
function yamlString(value) {
  const text = String(value === undefined || value === null ? '' : value)
    .replace(/\r\n/g, '\n')
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\n/g, '\\n')
    .replace(/\t/g, '\\t');
  return `"${text}"`;
}

function renderOpencodeAgent(parsedAgent, options = {}) {
  const name = parsedAgent.frontmatter.name || parsedAgent.name;
  const description = parsedAgent.frontmatter.description || '';
  const maxChars = options.maxChars === undefined ? 4000 : Number(options.maxChars);
  const body = maxChars > 0 && parsedAgent.body.length > maxChars
    ? `${parsedAgent.body.slice(0, maxChars)}\n\n[Truncated by Citadel projection. See the canonical agent definition for full instructions.]`
    : parsedAgent.body;

  const frontmatter = [
    '---',
    `# ${GENERATED_HEADER}`,
    `# Source: agents/${name}.md`,
    `description: ${yamlString(description)}`,
    `mode: ${SUBAGENT_MODE}`,
  ];
  if (options.model) frontmatter.push(`model: ${yamlString(options.model)}`);
  frontmatter.push('---', '');

  return `${frontmatter.join('\n')}${body.trim()}\n`;
}

function projectOpencodeAgents(options = {}) {
  const citadelRoot = options.citadelRoot || path.resolve(__dirname, '..', '..', '..');
  const projectRoot = options.projectRoot || process.cwd();
  const dryRun = options.dryRun === true;

  const sourceBase = path.join(citadelRoot, 'agents');
  const targetBase = path.join(projectRoot, '.opencode', 'agent');
  const agentFiles = options.agentName
    ? [`${options.agentName}.md`]
    : fs.readdirSync(sourceBase).filter((name) => name.endsWith('.md')).sort();

  const results = [];
  for (const agentFile of agentFiles) {
    const parsedAgent = loadAgent(path.join(sourceBase, agentFile));
    if (parsedAgent.errors && parsedAgent.errors.length > 0) {
      throw new Error(`Agent "${parsedAgent.name}" has validation errors: ${parsedAgent.errors.join(', ')}`);
    }
    const name = parsedAgent.frontmatter.name || parsedAgent.name;
    const targetPath = path.join(targetBase, `${name}.md`);
    const content = renderOpencodeAgent(parsedAgent, options);

    if (!dryRun) {
      ensureDir(path.dirname(targetPath));
      fs.writeFileSync(targetPath, content, 'utf8');
    }
    results.push({ name, targetPath, bytes: Buffer.byteLength(content), dryRun });
  }
  return results;
}

module.exports = Object.freeze({
  GENERATED_HEADER,
  projectOpencodeAgents,
  renderOpencodeAgent,
  yamlString,
});
