#!/usr/bin/env node

'use strict';

// Projects Citadel's canonical agents/*.md into .opencode/agent/*.md.
//
// opencode's agent loader (config/agent.ts) globs {agent,agents}/**/*.md, takes
// the agent NAME FROM THE FILE PATH rather than frontmatter, and uses the
// markdown body as the prompt. Its schema (core/v1/config/agent.ts) carries a
// Record rest, so unknown frontmatter keys are tolerated and folded into
// `options` — but only the documented keys are emitted here.

const fs = require('fs');
const path = require('path');
const { loadAgent } = require('../../../core/agents/parse-agent');

const GENERATED_HEADER = 'Generated by Citadel. Do not edit manually.';

// opencode agent modes. Citadel agents are all spawned as subagents.
const SUBAGENT_MODE = 'subagent';

function ensureDir(dir) {
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
}

// YAML scalar quoting for a frontmatter value that may contain colons, hashes,
// newlines, or quotes. Double-quoted style with escapes is valid YAML and avoids
// depending on a YAML writer.
function yamlString(value) {
  const text = String(value === undefined || value === null ? '' : value)
    .replace(/\r\n/g, '\n')
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\n/g, '\\n')
    .replace(/\t/g, '\\t');
  return `"${text}"`;
}

// Citadel agents declare tool access the Claude Code way: an allow-list in
// `tools` and/or a deny-list in `disallowedTools`. opencode has no such field --
// its markdown frontmatter takes a `permission` map, which it compiles into
// {permission, pattern, action} rules. Dropping the restrictions therefore does
// not degrade to "restricted by default", it degrades to opencode's defaults,
// which allow edits and shell execution. A read-only reviewer projected without
// this can write files and run commands.
//
// The mapping was read off a live opencode 1.18.30 instance rather than guessed:
// an agent declaring `permission: {edit: deny, bash: deny, webfetch: deny}`
// resolves to exactly those three deny rules via GET /agent. `tools: {write:
// false}` compiles to no rule at all -- opencode has no separate write
// permission, `edit` covers it -- which is why the deny-list is expressed through
// `permission` and not through a tools map.
const OPENCODE_PERMISSION_BY_TOOL = Object.freeze({
  edit: ['Edit', 'Write', 'MultiEdit', 'NotebookEdit', 'apply_patch'],
  bash: ['Bash', 'BashOutput', 'KillShell'],
  webfetch: ['WebFetch', 'WebSearch'],
});

// Only permissions opencode can actually gate. Read/Grep/Glob have no deny key,
// so an agent restricted to them is expressed by denying everything else.
const GATEABLE_PERMISSIONS = Object.freeze(Object.keys(OPENCODE_PERMISSION_BY_TOOL));

function toolListOf(value) {
  if (Array.isArray(value)) return value.map((item) => String(item).trim()).filter(Boolean);
  if (typeof value === 'string' && value.trim()) {
    return value.split(',').map((item) => item.trim()).filter(Boolean);
  }
  return [];
}

/**
 * Translate Citadel tool restrictions into an opencode permission map.
 *
 * A permission is denied when the agent explicitly disallows a tool that maps to
 * it, or when the agent declares an allow-list that grants no tool mapping to it.
 * An agent with neither field is unrestricted and gets no permission block.
 */
function opencodePermissionsFor(frontmatter = {}) {
  const allowed = toolListOf(frontmatter.tools);
  const disallowed = toolListOf(frontmatter.disallowedTools);
  if (allowed.length === 0 && disallowed.length === 0) return {};

  const has = (list, names) => names.some(
    (name) => list.some((item) => item.toLowerCase() === name.toLowerCase()),
  );

  const permissions = {};
  for (const permission of GATEABLE_PERMISSIONS) {
    const tools = OPENCODE_PERMISSION_BY_TOOL[permission];
    const explicitlyDenied = has(disallowed, tools);
    // An allow-list is exhaustive: anything it does not name is not granted.
    const withheld = allowed.length > 0 && !has(allowed, tools);
    if (explicitlyDenied || withheld) permissions[permission] = 'deny';
  }
  return permissions;
}

function renderOpencodeAgent(parsedAgent, options = {}) {
  const name = parsedAgent.frontmatter.name || parsedAgent.name;
  const description = parsedAgent.frontmatter.description || '';
  const maxChars = options.maxChars === undefined ? 4000 : Number(options.maxChars);
  const body = maxChars > 0 && parsedAgent.body.length > maxChars
    ? `${parsedAgent.body.slice(0, maxChars)}\n\n[Truncated by Citadel projection. See the canonical agent definition for full instructions.]`
    : parsedAgent.body;

  const frontmatter = [
    '---',
    `# ${GENERATED_HEADER}`,
    `# Source: agents/${name}.md`,
    `description: ${yamlString(description)}`,
    `mode: ${SUBAGENT_MODE}`,
  ];
  if (options.model) frontmatter.push(`model: ${yamlString(options.model)}`);

  // Restrictions must survive the projection or the agent is more capable on
  // opencode than it is on Claude Code.
  const permissions = opencodePermissionsFor(parsedAgent.frontmatter);
  const permissionKeys = Object.keys(permissions);
  if (permissionKeys.length) {
    frontmatter.push('permission:');
    for (const key of permissionKeys) frontmatter.push(`  ${key}: ${permissions[key]}`);
  }

  frontmatter.push('---', '');

  return `${frontmatter.join('\n')}${body.trim()}\n`;
}

function projectOpencodeAgents(options = {}) {
  const citadelRoot = options.citadelRoot || path.resolve(__dirname, '..', '..', '..');
  const projectRoot = options.projectRoot || process.cwd();
  const dryRun = options.dryRun === true;

  const sourceBase = path.join(citadelRoot, 'agents');
  const targetBase = path.join(projectRoot, '.opencode', 'agent');
  const agentFiles = options.agentName
    ? [`${options.agentName}.md`]
    : fs.readdirSync(sourceBase).filter((name) => name.endsWith('.md')).sort();

  const results = [];
  for (const agentFile of agentFiles) {
    const parsedAgent = loadAgent(path.join(sourceBase, agentFile));
    if (parsedAgent.errors && parsedAgent.errors.length > 0) {
      throw new Error(`Agent "${parsedAgent.name}" has validation errors: ${parsedAgent.errors.join(', ')}`);
    }
    const name = parsedAgent.frontmatter.name || parsedAgent.name;
    const targetPath = path.join(targetBase, `${name}.md`);
    const content = renderOpencodeAgent(parsedAgent, options);

    if (!dryRun) {
      ensureDir(path.dirname(targetPath));
      fs.writeFileSync(targetPath, content, 'utf8');
    }
    results.push({ name, targetPath, bytes: Buffer.byteLength(content), dryRun });
  }
  return results;
}

module.exports = Object.freeze({
  GENERATED_HEADER,
  projectOpencodeAgents,
  renderOpencodeAgent,
  opencodePermissionsFor,
  OPENCODE_PERMISSION_BY_TOOL,
  yamlString,
});
